//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedback_id { get; set; }
        public int product_id { get; set; }
        public int account_id { get; set; }
        public double rating { get; set; }
        public string comment { get; set; }
    
        public virtual account account { get; set; }
        public virtual product product { get; set; }
    }
}
