//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staff_id { get; set; }
        public int store_id { get; set; }
        public int position_id { get; set; }
        public int person_id { get; set; }
    
        public virtual person person { get; set; }
        public virtual position position { get; set; }
        public virtual store store { get; set; }
    }
}
