//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int product_id { get; set; }
        public int store_id { get; set; }
        public int quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
    }
}
