//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseAllInfoView
    {
        public int product_id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string road { get; set; }
        public string house { get; set; }
        public string flat { get; set; }
        public string zip_code { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public int quantity { get; set; }
    }
}
